# Generated by Django 5.0.7 on 2024-11-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_smart', '0003_alter_temperaturadata_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='sensor_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
