# Generated by Django 5.0.7 on 2024-11-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_smart', '0004_sensor_sensor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contadordata',
            name='valor',
            field=models.FloatField(default=0.0),
        ),
    ]
